apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: chatdemo
  annotations:
    app.oam.dev/publishVersion: rasa-mem3gi
  namespace: default
spec:
  components:
  - name: chatdemo-bot
    type: rasa-chatbot
    properties:
      name: chatdemo-bot
      rasaImage: healthidpuaeacr.azurecr.io/chatdemo-bot-rasa:c8ff472
      actionsImage: healthidpuaeacr.azurecr.io/chatdemo-bot-actions:c8ff472
      image: healthidpuaeacr.azurecr.io/chatdemo-bot-rasa:c8ff472
      resources:
        cpu: 500m
        memory: 3Gi
